In [2]:
import numpy as np
import random

In [2]:
# Basic Array Creation
arr = np.array([1,2,3,4])
arr 

array([1, 2, 3, 4])

In [7]:
a = [1,2,3.5,'hello']
b = [1,2,3.5]

In [12]:
a

[1, 2, 3.5, 'hello']

In [13]:
np.array(a)


array(['1', '2', '3.5', 'hello'], dtype='<U32')

In [14]:
b

[1, 2, 3.5]

In [15]:
np.array(b)

array([1. , 2. , 3.5])

In [16]:
l = [[1,2,3],[4,5,6],[7,9,8]]
l

[[1, 2, 3], [4, 5, 6], [7, 9, 8]]

In [17]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 9, 8]])

In [19]:
arr = np.arange(1,11,2)
arr 

array([1, 3, 5, 7, 9])

In [20]:
arr = np.zeros((4,8)) # Rows, Columns
arr 

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [22]:
arr = np.ones((6,6)) # Rows, Columns
arr 

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [25]:
arr = np.linspace(0,1,100) # Prints 100 elements between 0 and 1
arr 

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

In [31]:
np.random.rand(10)

array([0.05948836, 0.0207155 , 0.556266  , 0.24495797, 0.2953677 ,
       0.48086098, 0.45177684, 0.74494303, 0.69426868, 0.98887514])

In [ ]:
np.random.randn(10) # Creates an array between the values 3 and -3

In [32]:
np.random.randint(10,20,10)

array([11, 13, 18, 17, 12, 16, 11, 17, 16, 10], dtype=int32)

In [35]:
arr = np.array([[1,2,3], [4,5,6], [7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [36]:
arr.shape # Prints rows and columns of array

(3, 3)

In [37]:
arr.size

9

In [38]:
arr.dtype 

dtype('int64')

In [40]:
arr.min()

np.int64(1)

In [41]:
arr.max()

np.int64(9)

In [42]:
arr.sum()

np.int64(45)

In [43]:
np.sum(arr,axis = 0) # Calculates sum of columns

array([12, 15, 18])

In [44]:
np.sum(arr,axis = 1) # Calculates sum of rows

array([ 6, 15, 24])

In [45]:
arr.mean()

np.float64(5.0)

In [46]:
arr.std()

np.float64(2.581988897471611)

In [47]:
arr.argmax() 

np.int64(8)

In [48]:
arr.argmin() 

np.int64(0)

In [49]:
arr = np.arange(1,31)
arr 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [52]:
arr.reshape(6,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [4]:
# Numpy Indexing and Slicing of Vectors 
arr = np.arange(11,21)
arr 

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [9]:
arr[4]

np.int64(15)

In [5]:
arr[:5]

array([11, 12, 13, 14, 15])

In [6]:
arr[2:]

array([13, 14, 15, 16, 17, 18, 19, 20])

In [8]:
arr[::2]

array([11, 13, 15, 17, 19])

In [11]:
arr = np.arange(1,31).reshape(6,5)
arr 

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [12]:
arr[5]

array([26, 27, 28, 29, 30])

In [13]:
arr[5,4]

np.int64(30)

In [14]:
arr[0:2,1:3]

array([[2, 3],
       [7, 8]])

In [15]:
arr[3:,3:]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [17]:
arr[:,2]

array([ 3,  8, 13, 18, 23, 28])

In [18]:
# Boolean Indexing
bool_index = arr % 2 ==0
bool_index

array([[False,  True, False,  True, False],
       [ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True]])

In [19]:
arr = arr[bool_index]
arr 

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [5]:
# Array Operations
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])

In [6]:
a1+a2

array([ 7,  9, 11, 13, 15])

In [8]:
a1-a2 

array([-5, -5, -5, -5, -5])

In [9]:
a1/a2 

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [10]:
a1//a2 

array([0, 0, 0, 0, 0])

In [11]:
a1**a2 

array([      1,     128,    6561,  262144, 9765625])

In [12]:
# Broadcasting 
l = [10,20,30,40]
arr = np.array(l) 

In [14]:
arr + 10

array([20, 30, 40, 50])

In [15]:
arr2 = np.arange(1,26).reshape(5,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [17]:
arr2 = arr2 +10 # Changes in the arr2 itself

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [18]:
# Deep and Shallow Copy 
a = np.arange(1,21)
a 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [21]:
slice = a[:5]
slice = slice *10
slice 

array([10, 20, 30, 40, 50])

In [22]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [24]:
a[4:6] *10

array([50, 60])

In [28]:
b = a # Deep Copy
b[0] = 99
a 

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [29]:
b = a.copy()
b[2] = 101
a 

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [30]:
b

array([ 99,   2, 101,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20])

In [31]:
# Matrix Multiplication
A = np.array([[1,2], [3,4]])
B = np.array([[5,6], [7,8]])

In [32]:
A @ B 

array([[19, 22],
       [43, 50]])

In [33]:
np.dot(A,B) 

array([[19, 22],
       [43, 50]])

In [34]:
A

array([[1, 2],
       [3, 4]])

In [35]:
A.T

array([[1, 3],
       [2, 4]])

In [36]:
# Advance Array Manipulation
# Stacking 
a = np.array([1,2,3,4])
b = np.array([5,6,7,8]) 

In [37]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [40]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [41]:
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [42]:
np.row_stack((a,b))

C:\Users\HP\AppData\Local\Temp\ipykernel_3328\1307586492.py:1: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  np.row_stack((a,b))


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [44]:
# Spliting Array 
c = np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [46]:
np.hsplit(c,4)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [48]:
a = np.vsplit(c,2)

In [49]:
for i in a:
    print(i)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]
